// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-3wCmD9-OaYTvdJ2lfQskHfw1miwXiwQ',
    appId: '1:711064474177:web:71fde0ccbac9ded6c7ecc0',
    messagingSenderId: '711064474177',
    projectId: 'si-jawa',
    authDomain: 'si-jawa.firebaseapp.com',
    storageBucket: 'si-jawa.appspot.com',
    measurementId: 'G-6WKB4YDR11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6CcvGMIY95Em10z0oooce1RmcUBMcfbU',
    appId: '1:711064474177:android:854d096ab04fc4a9c7ecc0',
    messagingSenderId: '711064474177',
    projectId: 'si-jawa',
    storageBucket: 'si-jawa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QA9hwsb4tgnQ76VvAcbdGKHMiv-pflA',
    appId: '1:711064474177:ios:f5dc41ad71d978cbc7ecc0',
    messagingSenderId: '711064474177',
    projectId: 'si-jawa',
    storageBucket: 'si-jawa.appspot.com',
    iosBundleId: 'com.example.sijawa',
  );
}
